/**
 * @externs
 * @suppress {duplicate,checkTypes}
 */
// NOTE: generated by tsickle, do not edit.
// externs from src/app/App.ts:
// externs from C:/Users/orenm/Documents/GitHub/minimal-case-tsickle-fail/src/module/Module.ts:
/**
 * @record
 * @struct
 */
function IPointless() {}
 /** @type {?} */
IPointless.prototype.label;
// externs from C:/Users/orenm/Documents/GitHub/minimal-case-tsickle-fail/src/utils/utils.ts:
